export const GET_CHANNEL_MESSAGE_REQUEST = "GET_CHANNEL_MESSAGE_REQUEST";
export const GET_CHANNEL_MESSAGE_SUCCESS = "GET_CHANNEL_MESSAGE_SUCCESS";
export const GET_CHANNEL_MESSAGE_FAILURE = "GET_CHANNEL_MESSAGE_FAILURE";

export const GET_PRIVATE_CHAT_REQUEST = "GET_PRIVATE_CHAT_REQUEST";
export const GET_PRIVATE_CHAT_SUCCESS = "GET_PRIVATE_CHAT_SUCCESS";
export const GET_PRIVATE_CHAT_FAILURE = "GET_PRIVATE_CHAT_FAILURE";

export const GET_PRIVATE_MESSAGE_REQUEST = "GET_PRIVATE_MESSAGE_REQUEST";
export const GET_PRIVATE_MESSAGE_SUCCESS = "GET_PRIVATE_MESSAGE_SUCCESS";
export const GET_PRIVATE_MESSAGE_FAILURE = "GET_PRIVATE_MESSAGE_FAILURE";

export const LIKE_UNLIKE_MESSAGE_SUCCESS = "LIKE_UNLIKE_MESSAGE_SUCCESS";
export const LIKE_UNLIKE_PRIVATE_MESSAGE_SUCCESS =
  "LIKE_UNLIKE_PRIVATE_MESSAGE_SUCCESS";

export const APPEND_MESSAGE = "APPEND_MESSAGE";
export const APPEND_PRIVATE_MESSAGE = "APPEND_PRIVATE_MESSAGE";
export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS";
export const DELETE_PRIVATE_MESSAGE_SUCCESS = "DELETE_PRIVATE_MESSAGE_SUCCESS";
export const UPDATE_PRIVATE_CHAT_SUCCESS = "UPDATE_PRIVATE_CHAT_SUCCESS";
export const SET_ACTIVE_PRIVATE_CHAT = "SET_ACTIVE_PRIVATE_CHAT";
