export const SET_IS_MOBILE_SIZE = "SET_IS_MOBILE_SIZE";
export const SET_VISIBLE_SIDE_MENU = "SET_VISIBLE_SIDE_MENU";
export const SET_LOGIN_MODAL_VISIBLE = "SET_LOGIN_MODAL_VISIBLE";
export const SET_LOGIN_MODAL_INVISIBLE = "SET_LOGIN_MODAL_INVISIBLE";
export const SET_REGISTER_MODAL_VISIBLE = "SET_REGISTER_MODAL_VISIBLE";
export const SET_REGISTER_MODAL_INVISIBLE = "SET_REGISTER_MODAL_INVISIBLE";
export const SET_SPACE_SEARCHED = "SET_SPACE_SEARCHED";
