export const GET_ME_REQUEST = "GET_ME_REQUEST";
export const GET_ME_SUCCESS = "GET_ME_SUCCESS";
export const GET_ME_FAILURE = "GET_ME_FAILURE";
export const UPLOAD_PICTURE_REQUEST = "UPLOAD_PICTURE_REQUEST";
export const UPLOAD_PICTURE_SUCCESS = "UPLOAD_PICTURE_SUCCESS";
export const UPLOAD_PICTURE_FAILURE = "UPLOAD_PICTURE_FAILURE";
